#!/usr/bin/env bash
# click-jackalope.sh
# Usage: click-jackalope.sh -u <url> [-e] [-s] [-f <filename>] [-h]
# -u <url>       : URL to load in the iframe (required)
# -e             : execute/open the generated html (optional)
# -s             : add iframe sandboxing to the generated page (optional)
# -f <filename>  : output filename (default: clickjack_test.html)
# -h             : help

set -euo pipefail

FILE="clickjack_test.html"
OPEN=false
SANDBOX=false
URL=""

print_help() {
  cat <<EOF
click-jackalope.sh - quick clickjacking proof-of-concept page generator

Usage:
  ./click-jackalope.sh -u "https://target.example" [-e] [-s] [-f out.html]

Options:
  -u URL        Target URL to embed in iframe (required)
  -e            Open the generated HTML with the system default browser
  -s            Add iframe sandboxing to the generated HTML
  -f FILENAME   Output filename (default: clickjack_test.html)
  -h            Show this help
EOF
}

escape_html() {
  local value="$1"
  value=${value//&/&amp;}
  value=${value//</&lt;}
  value=${value//>/&gt;}
  value=${value//\"/&quot;}
  value=${value//\'/&#x27;}
  printf '%s' "$value"
}

# Parse options
while getopts ":u:esf:h" opt; do
  case ${opt} in
    u ) URL="$OPTARG" ;;
    e ) OPEN=true ;;
    s ) SANDBOX=true ;;
    f ) FILE="$OPTARG" ;;
    h )
      print_help
      exit 0
      ;;
    \? )
      echo "Invalid option: -$OPTARG" >&2
      print_help
      exit 2
      ;;
    : )
      echo "Option -$OPTARG requires an argument." >&2
      print_help
      exit 2
      ;;
  esac
done

# Validate
if [[ -z "$URL" ]]; then
  echo "ERROR: target URL is required (-u)." >&2
  print_help
  exit 2
fi

# Basic normalization/check (not exhaustive)
if [[ ! "$URL" =~ ^https?:// ]]; then
  echo "WARNING: URL does not start with http:// or https://. Prepending https://"
  URL="https://$URL"
fi

ESCAPED_URL="$(escape_html "$URL")"
SANDBOX_ATTR=""
SANDBOX_NOTE="Iframe sandboxing is disabled to better match a real clickjacking attempt."

if $SANDBOX; then
  SANDBOX_ATTR=' sandbox=""'
  SANDBOX_NOTE="Iframe sandboxing is enabled for this test."
fi

# Create HTML safely
cat > "$FILE" <<HTML
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Clickjacking test: iframe of $ESCAPED_URL</title>
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <style>
    body { margin: 0; display: flex; flex-direction: column; min-height: 100vh; font-family: sans-serif; background: #f2f4f7; color: #17202a; }
    header { padding: 10px 14px; background: #17202a; color: #f8f9f9; font-size: 14px; }
    main { flex: 1; display: flex; align-items: center; justify-content: center; padding: 16px; }
    iframe { width: 90vw; height: 85vh; border: 4px solid #2c3e50; background: white; box-shadow: 0 8px 24px rgba(0,0,0,0.18); }
    footer { padding: 8px 14px; background: #ecf0f1; color: #34495e; font-size: 12px; }
  </style>
</head>
<body>
  <header>Click-Jackalope test page. Embedded target: ${ESCAPED_URL}</header>
  <main>
    <iframe src="${ESCAPED_URL}" title="click-jackalope-test"${SANDBOX_ATTR}></iframe>
  </main>
  <footer>Generated by Click-Jackalope. ${SANDBOX_NOTE}</footer>
</body>
</html>
HTML

echo "Wrote $FILE (target: $URL, sandbox: $SANDBOX)"

if $OPEN; then
  # Cross-platform open
  if command -v xdg-open >/dev/null 2>&1; then
    xdg-open "$FILE" >/dev/null 2>&1 || echo "Failed to open $FILE with xdg-open"
  elif command -v open >/dev/null 2>&1; then
    open "$FILE" >/dev/null 2>&1 || echo "Failed to open $FILE with open"
  elif command -v start >/dev/null 2>&1; then
    # 'start' is typically a Windows cmd builtin; in Git Bash you can use 'cmd.exe /c start'
    cmd.exe /c start "" "$(cygpath -w "$PWD/$FILE")" >/dev/null 2>&1 || echo "Failed to open $FILE with start"
  else
    echo "No known method found to open the file automatically. Please open $FILE manually."
  fi
fi

exit 0
