package com.clickjackalope.burp;

final class ClickJackalopeHtmlGenerator
{
    private ClickJackalopeHtmlGenerator()
    {
    }

    static String build(String url, boolean sandboxIframe)
    {
        String escapedUrl = escapeHtml(url);
        String sandboxAttribute = sandboxIframe ? " sandbox=\"\"" : "";
        String sandboxNotice = sandboxIframe
            ? "Iframe sandboxing is enabled for this test."
            : "Iframe sandboxing is disabled to better match a real clickjacking attempt.";

        return """
            <!doctype html>
            <html lang="en">
            <head>
              <meta charset="utf-8" />
              <title>Clickjacking test: iframe of %s</title>
              <meta name="viewport" content="width=device-width,initial-scale=1" />
              <style>
                body { margin: 0; display: flex; flex-direction: column; min-height: 100vh; font-family: sans-serif; background: #f2f4f7; color: #17202a; }
                header { padding: 10px 14px; background: #17202a; color: #f8f9f9; font-size: 14px; }
                main { flex: 1; display: flex; align-items: center; justify-content: center; padding: 16px; }
                iframe { width: 90vw; height: 85vh; border: 4px solid #2c3e50; background: white; box-shadow: 0 8px 24px rgba(0, 0, 0, 0.18); }
                footer { padding: 8px 14px; background: #ecf0f1; color: #34495e; font-size: 12px; }
              </style>
            </head>
            <body>
              <header>Click-Jackalope test page. Embedded target: %s</header>
              <main>
                <iframe src="%s" title="click-jackalope-test"%s></iframe>
              </main>
              <footer>Generated by Click-Jackalope. %s</footer>
            </body>
            </html>
            """.formatted(escapedUrl, escapedUrl, escapedUrl, sandboxAttribute, sandboxNotice);
    }

    private static String escapeHtml(String value)
    {
        return value
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;")
            .replace("'", "&#x27;");
    }
}
