package com.clickjackalope.burp;

final class ClickJackalopeHtmlGenerator
{
    private ClickJackalopeHtmlGenerator()
    {
    }

    static String build(String url, boolean sandboxIframe, ClickJackalopeTemplate template)
    {
        String escapedUrl = escapeHtml(url);
        String sandboxAttribute = sandboxIframe ? " sandbox=\"\"" : "";
        String sandboxNotice = sandboxIframe
            ? "Iframe sandboxing is enabled for this test."
            : "Iframe sandboxing is disabled to better match a real clickjacking attempt.";

        String body = switch (template)
        {
            case STANDARD -> standardBody(escapedUrl, sandboxAttribute, sandboxNotice);
            case DECOY_LOGIN -> decoyLoginBody(escapedUrl, sandboxAttribute, sandboxNotice);
            case BANNER_LURE -> bannerLureBody(escapedUrl, sandboxAttribute, sandboxNotice);
        };

        return """
            <!doctype html>
            <html lang="en">
            <head>
              <meta charset="utf-8" />
              <title>Clickjacking test: iframe of %s</title>
              <meta name="viewport" content="width=device-width,initial-scale=1" />
            </head>
            <body>
              %s
            </body>
            </html>
            """.formatted(escapedUrl, body);
    }

    private static String standardBody(String escapedUrl, String sandboxAttribute, String sandboxNotice)
    {
        return """
            <style>
              body { margin: 0; display: flex; flex-direction: column; min-height: 100vh; font-family: sans-serif; background: #f2f4f7; color: #17202a; }
              header { padding: 10px 14px; background: #17202a; color: #f8f9f9; font-size: 14px; }
              main { flex: 1; display: flex; align-items: center; justify-content: center; padding: 16px; }
              iframe { width: 90vw; height: 85vh; border: 4px solid #2c3e50; background: white; box-shadow: 0 8px 24px rgba(0, 0, 0, 0.18); }
              footer { padding: 8px 14px; background: #ecf0f1; color: #34495e; font-size: 12px; }
            </style>
            <header>Click-Jackalope test page. Embedded target: %s</header>
            <main>
              <iframe src="%s" title="click-jackalope-test"%s></iframe>
            </main>
            <footer>Generated by Click-Jackalope. %s</footer>
            """.formatted(escapedUrl, escapedUrl, sandboxAttribute, sandboxNotice);
    }

    private static String decoyLoginBody(String escapedUrl, String sandboxAttribute, String sandboxNotice)
    {
        return """
            <style>
              body { margin: 0; min-height: 100vh; font-family: sans-serif; background: radial-gradient(circle at top, #14324a 0%%, #09111a 65%%); color: #ecf4f8; overflow: hidden; }
              .frame-wrap { position: fixed; inset: 0; }
              iframe { width: 100%%; height: 100%%; border: 0; }
              .overlay {
                position: relative;
                z-index: 2;
                max-width: 380px;
                margin: 11vh auto 0;
                background: rgba(250, 252, 253, 0.95);
                color: #13212d;
                border-radius: 16px;
                padding: 22px;
                box-shadow: 0 24px 60px rgba(0,0,0,0.35);
              }
              h1 { margin: 0 0 6px; font-size: 24px; }
              p { margin: 0 0 14px; color: #41576a; }
              label { display: block; font-size: 13px; font-weight: 700; margin-bottom: 6px; }
              input { width: 100%%; margin-bottom: 12px; padding: 11px 12px; border-radius: 10px; border: 1px solid #c7d3dd; }
              button { width: 100%%; border: 0; border-radius: 10px; padding: 12px; background: #0b6bcb; color: white; font-weight: 700; }
              .foot { margin-top: 12px; font-size: 12px; color: #5c7081; }
            </style>
            <div class="frame-wrap">
              <iframe src="%s" title="click-jackalope-test"%s></iframe>
            </div>
            <div class="overlay">
              <h1>Continue Session</h1>
              <p>Use this template to demonstrate deceptive overlay positioning over a live framed page.</p>
              <label>Email</label>
              <input type="email" placeholder="user@example.test" />
              <label>Password</label>
              <input type="password" placeholder="password" />
              <button type="button">Sign in</button>
              <div class="foot">Embedded target: %s<br />%s</div>
            </div>
            """.formatted(escapedUrl, sandboxAttribute, escapedUrl, sandboxNotice);
    }

    private static String bannerLureBody(String escapedUrl, String sandboxAttribute, String sandboxNotice)
    {
        return """
            <style>
              body { margin: 0; min-height: 100vh; font-family: sans-serif; background: #f6f7eb; color: #14222e; }
              .topbar {
                position: sticky;
                top: 0;
                z-index: 3;
                padding: 14px 18px;
                background: #8a1538;
                color: #fff7e6;
                font-weight: 700;
                box-shadow: 0 8px 18px rgba(0,0,0,0.16);
              }
              .topbar span { display: block; font-size: 12px; font-weight: 400; opacity: 0.9; }
              main { padding: 18px; }
              .card { max-width: 960px; margin: 0 auto; background: white; border-radius: 18px; padding: 16px; box-shadow: 0 18px 40px rgba(0,0,0,0.12); }
              iframe { width: 100%%; height: 82vh; border: 0; border-radius: 12px; }
              .foot { margin-top: 10px; font-size: 12px; color: #5c6770; }
            </style>
            <div class="topbar">Action required: verify your session to continue<span>This template keeps a persistent lure banner above the embedded target.</span></div>
            <main>
              <div class="card">
                <iframe src="%s" title="click-jackalope-test"%s></iframe>
                <div class="foot">Embedded target: %s<br />%s</div>
              </div>
            </main>
            """.formatted(escapedUrl, sandboxAttribute, escapedUrl, sandboxNotice);
    }

    private static String escapeHtml(String value)
    {
        return value
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;")
            .replace("'", "&#x27;");
    }
}
